import {useEffect,useMemo,useState} from 'react';
import {Cloud,RefreshCw,Plus,X,Grid3X3} from 'lucide-react';
import {getData,post} from './api';
import {machineNames,mockOrders,Machine,Order} from './data';
import {MachineCard,Navbar,OrdersPanel,SummaryPanel} from './components';
import './index.css';

const initialMachines:Machine[]=machineNames.map((name,i)=>({id:i+1,name,orderId:['1','2','3','2','',''][i],colors:i===0?['#fff','#111','#2563eb','#ec4899']:i===1?['#ef4444','#fff']:i===2?['#2563eb','#fff']:i===3?['#ec4899','#fff']:[]}));
function App(){const [orders,setOrders]=useState<Order[]>(mockOrders);const [machines,setMachines]=useState<Machine[]>(initialMachines);const [mobile,setMobile]=useState(false);const [last,setLast]=useState(new Date());const [syncing,setSyncing]=useState(false);const [modal,setModal]=useState(false);const refresh=async()=>{if(syncing)return;setSyncing(true);try{const d=await getData();if(Array.isArray(d?.orders)&&d.orders.length){setOrders(d.orders)}if(Array.isArray(d?.machines)&&d.machines.length){setMachines(d.machines.map((m:any,i:number)=>({id:i+1,name:machineNames[i]||m.name,orderId:String(m.orderId||''),colors:Array.isArray(m.colors)?m.colors:[]})))}setLast(new Date())}catch{}finally{setSyncing(false)}};useEffect(()=>{refresh();const t=setInterval(refresh,5000);return()=>clearInterval(t)},[]);const updateMachine=(m:Machine)=>setMachines(ms=>ms.map(x=>x.id===m.id?m:x));const addOrder=async()=>{const client=prompt('Nombre del pedido');if(!client)return;const qty=Number(prompt('Cantidad','25')||25);const o:Order={id:'local-'+Date.now(),client,design:client,quantity:qty,produced:0,status:'Pendiente',delivery:'En día',priority:'normal'};setOrders(os=>[...os,o]);try{await post('addOrder',{client,design:client,quantity:qty,status:'Pendiente'})}catch{}setModal(false)};return <div className="app"><Navbar onMobile={()=>setMobile(v=>!v)}/>{mobile&&<div style={{position:'fixed',inset:'64px 0 auto 0',background:'#101416',borderBottom:'1px solid #252c30',zIndex:50,padding:12,display:'grid',gap:6}}><button className="btn" onClick={()=>setMobile(false)}>Producción agrupada</button><button className="btn" onClick={()=>setMobile(false)}>Pedidos</button><button className="btn" onClick={()=>setMobile(false)}>Diseños</button><button className="btn" onClick={()=>setMobile(false)}>Estadísticas</button><button className="btn" onClick={()=>setMobile(false)}>Configuración</button></div>}<main className="main"><section className="panel production-panel"><div className="panel-head"><div className="heading"><Grid3X3 className="heading-icon" size={25}/><div><h1>Producción agrupada</h1><p>La app junta automáticamente los mismos diseños.</p></div></div><div className="head-actions"><button className="btn" onClick={refresh}><RefreshCw size={15} className={syncing?'animate-spin':''}/>Sincronizar</button><button className="btn primary" onClick={addOrder}><Plus size={16}/>Añadir máquina</button></div></div><div className="machines">{machines.map(m=><MachineCard key={m.id} machine={m} orders={orders} onUpdate={updateMachine}/>)}</div></section><aside className="sidebar"><OrdersPanel orders={orders}/><SummaryPanel orders={orders} machines={machines}/></aside></main><footer className="footer">Dunno Producción v2.0 <span>•</span> Todos los cambios se sincronizan automáticamente <Cloud size={14}/></footer>{modal&&<div/>}</div>}
export default App;
